// Embeds the on-device AI (TensorFlow.js from cdnjs, MobileNetV2-0.35 feature vectors and
// BlazeFace from TF Hub) into carousel-sequencer.html between the AI markers, as inline script
// and base64 weights, so the page never fetches anything at runtime. Run: node tools/embed-ai.mjs
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
const cache = join(root, 'tools', '.ai-cache');
mkdirSync(cache, { recursive: true });
const TF = 'https://cdnjs.cloudflare.com/ajax/libs/tensorflow/4.22.0/tf.min.js';
const MODELS = {
  mnv2: 'https://tfhub.dev/google/tfjs-model/imagenet/mobilenet_v2_035_224/feature_vector/3/default/1/',
  blaze: 'https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/'
};
async function get(url, name, binary) {
  const p = join(cache, name);
  if (existsSync(p)) return binary ? readFileSync(p) : readFileSync(p, 'utf8');
  const r = await fetch(url);
  if (!r.ok) throw new Error(url + ' -> ' + r.status);
  const data = binary ? Buffer.from(await r.arrayBuffer()) : await r.text();
  writeFileSync(p, data);
  return data;
}
async function model(key) {
  const base = MODELS[key];
  const mj = JSON.parse(await get(base + 'model.json?tfjs-format=file', key + '.model.json'));
  const paths = mj.weightsManifest.flatMap((m) => m.paths);
  const parts = [];
  for (const p of paths) parts.push(await get(base + p + '?tfjs-format=file', key + '.' + p + '.bin', true));
  return { topology: mj.modelTopology, specs: mj.weightsManifest.flatMap((m) => m.weights), b64: Buffer.concat(parts).toString('base64') };
}
const tf = await get(TF, 'tf.min.js');
const mnv2 = await model('mnv2'), blaze = await model('blaze');
const json = JSON.stringify({ mnv2, blaze, version: 1, source: MODELS, tf: TF }).replace(/<\//g, '<\\/');
const block = `<!-- AI:begin (generated by tools/embed-ai.mjs; do not edit by hand) -->
<script id="tfjs">${tf.replace(/<\//g, '<\\/')}</script>
<script id="ai-models" type="application/json">${json}</script>
<!-- AI:end -->`;
const html = readFileSync(join(root, 'carousel-sequencer.html'), 'utf8');
const re = /<!-- AI:begin[\s\S]*?<!-- AI:end -->/;
// function replacers: a string replacement would expand $' and $& found inside tf.min.js
const out = re.test(html) ? html.replace(re, () => block) : html.replace('<script id="core">', () => block + '\n<script id="core">');
writeFileSync(join(root, 'carousel-sequencer.html'), out);
console.log('embedded: tf.min.js ' + (tf.length / 1e6).toFixed(2) + ' MB, models ' + (json.length / 1e6).toFixed(2) + ' MB; page ' + (out.length / 1e6).toFixed(2) + ' MB');
